server:
  port: 10000

spring:
  application:
    name: food-sas-service
  datasource:
    url: jdbc:mysql://127.0.0.1:4000/sas?useUnicode=true&connectTimeout=2000&socketTimeout=6000&rewriteBatchedStatements=TRUE&serverTimezone=Hongkong
    username: food
    password: food@2019
    hikari:
      maximum-pool-size: 20
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect:
          storage_engine: innodb
        jdbc:
          batch_size: 5000
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        naming:
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  jackson:
    locale: zh_CN
    #resources:
    # static-locations: ["classpath:/static/upload/"]
  # webflux:
  #   static-path-pattern: /uploads/**
  main:
    allow-bean-definition-overriding: true

swagger:
  groupName: 'sas-service-api'
  basePackage: 'com.food.sas.controller'


sms.TemplateCode: SMS_157445055
sms.SignName: 安全抽检
sms.accessKeyId: LTAIxGYss93KmEQM
sms.accessSecret: tcyo7lOD4WuM7DJrqgTOshhfHwZNLd




