server:
  port: 9666

spring:
  application:
    name: food-sas-service
  datasource:
    url: jdbc:mysql://39.98.172.236:3306/sas?useUnicode=true&connectTimeout=2000&socketTimeout=6000&autoReconnect=true&rewriteBatchedStatements=TRUE
    username: root
    password: 123456
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          batch_size: 5000
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        naming:
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect


swagger:
  groupName: 'sas-service-api'
  basePackage: 'com.food.sas.controller'

file-path: '/Users/temp/'