server:
  port: 10000

spring:
  application:
    name: food-sas-service
  datasource:
    url: jdbc:mysql://127.0.0.1:4000/sas?useUnicode=true&connectTimeout=2000&socketTimeout=6000&rewriteBatchedStatements=TRUE&serverTimezone=Hongkong
    username: food
    password: food@2019
    hikari:
      maximum-pool-size: 20
      auto-commit: true
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect:
          storage_engine: innodb
        jdbc:
          batch_size: 5000
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        naming:
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        query:
          plan_cache_max_size: 64
          plan_parameter_metadata_max_size: 32
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  jackson:
    locale: zh_CN
    serialization:
      write-dates-as-timestamps: true
  # webflux:
  #   static-path-pattern: /uploads/**
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    prefix: classpath:static/

swagger:
  groupName: 'sas-service-api'
  basePackage: 'com.food.sas.controller'

sms.TemplateCode: SMS_157445055
sms.SignName: 安全抽检
sms.accessKeyId: LTAIxGYss93KmEQM
sms.accessSecret: tcyo7lOD4WuM7DJrqgTOshhfHwZNLd




