server:
  port: 9666

spring:
  application:
    name: food-sas-service
  datasource:
    url: jdbc:mysql://localhost:3306/d_sas?useUnicode=true&connectTimeout=2000&socketTimeout=6000&autoReconnect=true&rewriteBatchedStatements=TRUE
    username: root
    password: root
  jpa:
    show-sql: true
    generate-ddl: true

swagger:
  groupName: 'sas-service-api'
  basePackage: 'com.food.sas.controller'

file-path: '/Users/temp/'